name: 'Check spelling'
description: 'Spell check commits'
author: 'jsoref'
branding:
  icon: 'edit-3'
  color: 'red'
inputs:
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
    default: "${{ github.token }}"
    required: true
  bucket:
    description: 'Container for spelling configuration'
    required: false
  project:
    description: 'Folder/Branch within bucket containing spelling configuration'
    required: false
  config:
    description: 'Spelling configuration directory'
    default: ".github/actions/spelling"
    required: false
  dictionary_url:
    description: "Location of dictionary (if you aren't providing one in your repository)"
    default: 'https://raw.githubusercontent.com/check-spelling/check-spelling/dictionary-\$DICTIONARY_VERSION/dict.txt'
    required: false
  dictionary_version:
    description: 'Version of the dictionary (only used if the url includes $DICTIONARY_VERSION)'
    default: "20200211"
    required: false
  debug:
    description: 'Debug'
    required: false
  experimental_apply_changes_via_bot:
    description: '(Experimental) Allow users to quote-reply to the bot comment to update the PR'
    default: "0"
    required: false
  experimental_parallel_jobs:
    description: 'Number of CPUs available for running checks'
    required: false
    default: '2'
  post_comment:
    description: 'Post comment with report'
    required: false
    default: '1'

runs:
  using: 'composite'
  steps:
    - run: >
        INPUT_GITHUB_TOKEN="${{ inputs.GITHUB_TOKEN }}"
        INPUT_BUCKET="${{ inputs.bucket }}"
        INPUT_PROJECT="${{ inputs.project }}"
        INPUT_CONFIG="${{ inputs.config }}"
        INPUT_DICTIONARY_VERSION="${{ inputs.dictionary_version }}"
        INPUT_DICTIONARY_URL="${{ inputs.dictionary_url }}"
        INPUT_EXPERIMENTAL_APPLY_CHANGES_VIA_BOT="${{ inputs.experimental_apply_changes_via_bot }}"
        INPUT_EXPERIMENTAL_PARALLEL_JOBS="${{ inputs.experimental_parallel_jobs }}"
        INPUT_POST_COMMENT="${{ inputs.post_comment }}"
        DEBUG="${{ inputs.debug }}"
        spellchecker=$GITHUB_ACTION_PATH
        $GITHUB_ACTION_PATH/unknown-words.sh
      shell: bash
